version: "3.9"

services:
  plexus:
    image: ghcr.io/mcowger/plexus:dev
    container_name: plexus
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - /mnt/plexus/config:/app/config
    environment:
      - LOG_LEVEL=info
      - CONFIG_FILE=/app/config/plexus.yaml
      - AUTH_JSON=/app/config/auth.json
      - DATABASE_URL=postgresql://plexus:plexus@plexusdb:5432/plexus
    depends_on:
      - plexusdb

  plexusdb:
    image: postgres:17-alpine
    container_name: plexusdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plexus
    volumes:
      - /mnt/plexus/db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

